name: ci_windows

on:
  push:
    paths:
      - "**/*.f"
      - "**/*.f90"
      - "**/*.py"
      - "**/*.m"
      - "**/meson.build"
      - ".github/workflows/ci_windows.yml"
  pull_request:
    paths:
      - "**/*.f"
      - "**/*.f90"
      - "**/*.py"
      - "**/*.m"
      - "**/meson.build"
      - ".github/workflows/ci_windows.yml"

jobs:

  cmake:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build -G "MinGW Makefiles"

    - run: cmake --build build --parallel
    - run: ctest --test-dir build

  # meson:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'

  #   - run: pip install -e .[tests]

  #   - run: meson setup build

  #   - run: meson test -C build -v

  #   - run: pytest
